# Importar librerias

In [1]:
import pandas as pd
import numpy as np

# Obtención de datos

In [2]:
ruta = r"C:\Users\Usuario\Desktop\Informes BCRA - Bancos\202510d\Entfin\Tec_Cont\esd\COMPLETO.TXT"

In [3]:
df = pd.read_csv(
    ruta,
    sep="\t",
    quotechar='"',
    encoding="latin1",
    header=None,
    engine="python"
)

# Análisis previo del dataset

In [4]:
df.head(10)

,0,1,2,3,4,5,6,7,8,9,10
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,202510,500110001000,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),2814492.63,10650244.05,19022919.16,20551842.19,20757186.83,N
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,202510,500110001010,TF.Sit.1: En situación normal (%),96.73,96.65,91.67,91.25,90.28,P
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,202510,500110001020,TF.Sit.2: Con seguimiento especial/Riesgo bajo...,0.99,1.53,2.78,3.02,3.51,P
3,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,202510,500110001030,TF.Sit.3: Con problemas/Riesgo medio (%),0.79,0.97,2.99,2.80,3.00,P
4,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,202510,500110001040,TF.Sit.4: Con alto riesgo de insolvencia/Riesg...,1.03,0.75,2.17,2.47,2.67,P
5,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,202510,500110001050,TF.Sit.5: Irrecuperable (%),0.46,0.11,0.39,0.45,0.55,P
6,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,202510,500110002000,TOTAL GARANTIZADO - Garantías Preferidas A y B...,8.88,10.84,11.33,11.37,11.63,P
7,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,202510,500110101000,CARTERA COMERCIAL ($),993461.97,4084769.98,6833389.91,7929119.22,7963092.49,N
8,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,202510,500110101001,Total cartera sobre financiaciones (%),35.30,38.35,35.92,38.58,38.36,P
9,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,202510,500110101010,C.COM.Sit.1: En situación normal (%),99.64,99.73,99.24,99.43,99.23,P

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2271 entries, 0 to 2270
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2271 non-null   object
 1   1       2271 non-null   object
 2   2       2271 non-null   int64
 3   3       2271 non-null   int64
 4   4       2271 non-null   object
 5   5       2271 non-null   float64
 6   6       2271 non-null   float64
 7   7       2271 non-null   float64
 8   8       2271 non-null   float64
 9   9       2271 non-null   float64
 10  10      2271 non-null   object
dtypes: float64(5), int64(2), object(4)
memory usage: 195.3+ KB

In [6]:
df.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

# Transformaciones

In [7]:
df1=df.copy()

In [8]:
# Eliminar columna 2
df1 = df1.drop(columns=2)

In [9]:
df1.head(10)

,0,1,3,4,5,6,7,8,9,10
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001000,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),2814492.63,10650244.05,19022919.16,20551842.19,20757186.83,N
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001010,TF.Sit.1: En situación normal (%),96.73,96.65,91.67,91.25,90.28,P
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001020,TF.Sit.2: Con seguimiento especial/Riesgo bajo...,0.99,1.53,2.78,3.02,3.51,P
3,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001030,TF.Sit.3: Con problemas/Riesgo medio (%),0.79,0.97,2.99,2.80,3.00,P
4,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001040,TF.Sit.4: Con alto riesgo de insolvencia/Riesg...,1.03,0.75,2.17,2.47,2.67,P
5,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001050,TF.Sit.5: Irrecuperable (%),0.46,0.11,0.39,0.45,0.55,P
6,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110002000,TOTAL GARANTIZADO - Garantías Preferidas A y B...,8.88,10.84,11.33,11.37,11.63,P
7,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110101000,CARTERA COMERCIAL ($),993461.97,4084769.98,6833389.91,7929119.22,7963092.49,N
8,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110101001,Total cartera sobre financiaciones (%),35.30,38.35,35.92,38.58,38.36,P
9,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110101010,C.COM.Sit.1: En situación normal (%),99.64,99.73,99.24,99.43,99.23,P

In [10]:
# Asignar situación a los códigos de línea

df1["situacion"] = (
    df1[3]
    .astype(str)
    .str[-2:]  # últimos dos dígitos
    .map({
        "10": "Situacion 1",
        "20": "Situacion 2",
        "30": "Situacion 3",
        "40": "Situacion 4",
        "50": "Situacion 5"
    })
)

In [11]:
# Verificar cambios realizados

df1.head(3)

,0,1,3,4,5,6,7,8,9,10,situacion
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001000,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),2814492.63,10650244.05,19022919.16,20551842.19,20757186.83,N,NaN
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001010,TF.Sit.1: En situación normal (%),96.73,96.65,91.67,91.25,90.28,P,Situacion 1
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001020,TF.Sit.2: Con seguimiento especial/Riesgo bajo...,0.99,1.53,2.78,3.02,3.51,P,Situacion 2

In [12]:
# Cambiar nombre a las columnas

df1 = df1.rename(columns={
    0: "codigo_entidad",
    1: "nombre_entidad",
    3: "codigo_linea",
    4: "denominacion",
    5: "dic_2023",
    6: "dic_2024",
    7: "set_2025",
    8: "oct_2025",
    9: "nov_2025",
    10: "formato"
})

In [13]:
# Verificar cambios realizados

df1.columns

Index(['codigo_entidad', 'nombre_entidad', 'codigo_linea', 'denominacion',
       'dic_2023', 'dic_2024', 'set_2025', 'oct_2025', 'nov_2025', 'formato',
       'situacion'],
      dtype='object')

In [14]:
cols_valor = [
    "dic_2023",
    "dic_2024",
    "set_2025",
    "oct_2025",
    "nov_2025"
]

In [15]:
df1 = df1.melt(
    id_vars=[
        "codigo_entidad",
        "nombre_entidad",
        "codigo_linea",
        "denominacion",
        "formato",
        "situacion"
    ],
    value_vars=cols_valor,
    var_name="periodo",
    value_name="valor"
)

In [16]:
df1["periodo"] = (
    df1["periodo"]
    .str.replace("valor_", "", regex=False)
)

In [17]:
# Verificar cambios realizados

df1.head(3)

,codigo_entidad,nombre_entidad,codigo_linea,denominacion,formato,situacion,periodo,valor
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001000,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),N,NaN,dic_2023,2814492.63
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001010,TF.Sit.1: En situación normal (%),P,Situacion 1,dic_2023,96.73
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001020,TF.Sit.2: Con seguimiento especial/Riesgo bajo...,P,Situacion 2,dic_2023,0.99

In [18]:
# Convertir a tipo fecha

map_fecha = {
    "dic_2023": "2023-12-31",
    "dic_2024": "2024-12-31",
    "set_2025": "2025-09-30",
    "oct_2025": "2025-10-31",
    "nov_2025": "2025-11-30"
}

df1["fecha"] = pd.to_datetime(df1["periodo"].map(map_fecha))

In [19]:
df1.head(3)

,codigo_entidad,nombre_entidad,codigo_linea,denominacion,formato,situacion,periodo,valor,fecha
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001000,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),N,NaN,dic_2023,2814492.63,2023-12-31
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001010,TF.Sit.1: En situación normal (%),P,Situacion 1,dic_2023,96.73,2023-12-31
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001020,TF.Sit.2: Con seguimiento especial/Riesgo bajo...,P,Situacion 2,dic_2023,0.99,2023-12-31

In [20]:
# Ordenar columnas

df1 = df1[
    [
        "codigo_entidad",
        "nombre_entidad",
        "codigo_linea",
        "denominacion",
        "situacion",
        "fecha",
        "periodo",
        "valor",
        "formato"
    ]
]

In [21]:
# Verificar cambios realizados

df1

,codigo_entidad,nombre_entidad,codigo_linea,denominacion,situacion,fecha,periodo,valor,formato
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001000,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),NaN,2023-12-31,dic_2023,2814492.63,N
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001010,TF.Sit.1: En situación normal (%),Situacion 1,2023-12-31,dic_2023,96.73,P
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001020,TF.Sit.2: Con seguimiento especial/Riesgo bajo...,Situacion 2,2023-12-31,dic_2023,0.99,P
3,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001030,TF.Sit.3: Con problemas/Riesgo medio (%),Situacion 3,2023-12-31,dic_2023,0.79,P
4,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001040,TF.Sit.4: Con alto riesgo de insolvencia/Riesg...,Situacion 4,2023-12-31,dic_2023,1.03,P
...,...,...,...,...,...,...,...,...,...
11350,AA910,10 PRIMEROS BANCOS PRIVADOS,500110301030,C.CAC.Sit.3: Riesgo medio (%),Situacion 3,2025-11-30,nov_2025,1.66,P
11351,AA910,10 PRIMEROS BANCOS PRIVADOS,500110301040,C.CAC.Sit.4: Riesgo alto (%),Situacion 4,2025-11-30,nov_2025,1.41,P
11352,AA910,10 PRIMEROS BANCOS PRIVADOS,500110301050,C.CAC.Sit.5: Irrecuperable (%),Situacion 5,2025-11-30,nov_2025,0.24,P
11353,AA910,10 PRIMEROS BANCOS PRIVADOS,500110302000,C.CAC.TOTAL GARANTIZADO - Garantías Preferidas...,NaN,2025-11-30,nov_2025,21.68,P
11354,AA910,10 PRIMEROS BANCOS PRIVADOS,500130003000,Previsiones por riesgo de incobrabilidad const...,NaN,2025-11-30,nov_2025,3534359.69,N

In [22]:
# Reemplazar los valores nan en la columna situación por total
df1['situacion'] = df1['situacion'].fillna('total')

In [23]:
# Cambiar valores de la columna formtao
df1['formato'] = df1['formato'].map({
    'N': 'monto',
    'P': 'porcentaje'
})

In [24]:
df1

,codigo_entidad,nombre_entidad,codigo_linea,denominacion,situacion,fecha,periodo,valor,formato
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001000,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),total,2023-12-31,dic_2023,2814492.63,monto
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001010,TF.Sit.1: En situación normal (%),Situacion 1,2023-12-31,dic_2023,96.73,porcentaje
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001020,TF.Sit.2: Con seguimiento especial/Riesgo bajo...,Situacion 2,2023-12-31,dic_2023,0.99,porcentaje
3,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001030,TF.Sit.3: Con problemas/Riesgo medio (%),Situacion 3,2023-12-31,dic_2023,0.79,porcentaje
4,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,500110001040,TF.Sit.4: Con alto riesgo de insolvencia/Riesg...,Situacion 4,2023-12-31,dic_2023,1.03,porcentaje
...,...,...,...,...,...,...,...,...,...
11350,AA910,10 PRIMEROS BANCOS PRIVADOS,500110301030,C.CAC.Sit.3: Riesgo medio (%),Situacion 3,2025-11-30,nov_2025,1.66,porcentaje
11351,AA910,10 PRIMEROS BANCOS PRIVADOS,500110301040,C.CAC.Sit.4: Riesgo alto (%),Situacion 4,2025-11-30,nov_2025,1.41,porcentaje
11352,AA910,10 PRIMEROS BANCOS PRIVADOS,500110301050,C.CAC.Sit.5: Irrecuperable (%),Situacion 5,2025-11-30,nov_2025,0.24,porcentaje
11353,AA910,10 PRIMEROS BANCOS PRIVADOS,500110302000,C.CAC.TOTAL GARANTIZADO - Garantías Preferidas...,total,2025-11-30,nov_2025,21.68,porcentaje
11354,AA910,10 PRIMEROS BANCOS PRIVADOS,500130003000,Previsiones por riesgo de incobrabilidad const...,total,2025-11-30,nov_2025,3534359.69,monto

In [25]:
# Eliminar registros que no corresponden a entidades financieras
df1 = df1[~df1['codigo_entidad'].str.startswith('AA', na=False)]

In [26]:
# Verificar cantidad de filas despues de la eliminación
print("Filas después:", len(df1))

Filas después: 9635

In [27]:
# Eliminar columnas codigo_linea y periodo
df1 = df1.drop(columns=['codigo_linea', 'periodo'], errors='ignore')

In [28]:
# Verificar eliminación de columnas
df1.columns

Index(['codigo_entidad', 'nombre_entidad', 'denominacion', 'situacion',
       'fecha', 'valor', 'formato'],
      dtype='object')

In [29]:
df1.head(30)

,codigo_entidad,nombre_entidad,denominacion,situacion,fecha,valor,formato
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),total,2023-12-31,2814492.63,monto
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.1: En situación normal (%),Situacion 1,2023-12-31,96.73,porcentaje
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.2: Con seguimiento especial/Riesgo bajo...,Situacion 2,2023-12-31,0.99,porcentaje
3,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.3: Con problemas/Riesgo medio (%),Situacion 3,2023-12-31,0.79,porcentaje
4,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.4: Con alto riesgo de insolvencia/Riesg...,Situacion 4,2023-12-31,1.03,porcentaje
5,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.46,porcentaje
6,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TOTAL GARANTIZADO - Garantías Preferidas A y B...,total,2023-12-31,8.88,porcentaje
7,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA COMERCIAL ($),total,2023-12-31,993461.97,monto
8,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,Total cartera sobre financiaciones (%),total,2023-12-31,35.30,porcentaje
9,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.1: En situación normal (%),Situacion 1,2023-12-31,99.64,porcentaje
10,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.2: Con seguimiento especial (%),Situacion 2,2023-12-31,0.22,porcentaje
11,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.3: Con problemas (%),Situacion 3,2023-12-31,0.00,porcentaje
12,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.4: Con alto riesgo de insolvencia (%),Situacion 4,2023-12-31,0.05,porcentaje
13,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.09,porcentaje
14,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.TOTAL GARANTIZADO - Garantías Preferidas...,total,2023-12-31,6.60,porcentaje
15,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA DE CONSUMO O VIVIENDA ($),total,2023-12-31,1134529.54,monto
16,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,Total cartera sobre financiaciones (%),total,2023-12-31,40.31,porcentaje
17,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.1: En situación normal (%),Situacion 1,2023-12-31,94.14,porcentaje
18,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,1.70,porcentaje
19,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,1.60,porcentaje
20,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.86,porcentaje
21,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.69,porcentaje
22,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.TOTAL GARANTIZADO - Garantías Preferidas...,total,2023-12-31,9.68,porcentaje
23,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA COMERCIAL ASIMILABLE A CONSUMO ($),total,2023-12-31,686501.13,monto
24,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,Total cartera sobre financiaciones (%),total,2023-12-31,24.39,porcentaje
25,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.1: En situación normal (%),Situacion 1,2023-12-31,96.78,porcentaje
26,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,0.91,porcentaje
27,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,0.60,porcentaje
28,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.07,porcentaje
29,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.64,porcentaje

In [30]:
# Eliminar registros donde denominación sea igual a "Total cartera sobre financiaciones (%)""

df1 = df1[df1["denominacion"] != "Total cartera sobre financiaciones (%)"].copy()

In [31]:
df1.head(30)

,codigo_entidad,nombre_entidad,denominacion,situacion,fecha,valor,formato
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),total,2023-12-31,2814492.63,monto
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.1: En situación normal (%),Situacion 1,2023-12-31,96.73,porcentaje
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.2: Con seguimiento especial/Riesgo bajo...,Situacion 2,2023-12-31,0.99,porcentaje
3,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.3: Con problemas/Riesgo medio (%),Situacion 3,2023-12-31,0.79,porcentaje
4,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.4: Con alto riesgo de insolvencia/Riesg...,Situacion 4,2023-12-31,1.03,porcentaje
5,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.46,porcentaje
6,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TOTAL GARANTIZADO - Garantías Preferidas A y B...,total,2023-12-31,8.88,porcentaje
7,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA COMERCIAL ($),total,2023-12-31,993461.97,monto
9,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.1: En situación normal (%),Situacion 1,2023-12-31,99.64,porcentaje
10,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.2: Con seguimiento especial (%),Situacion 2,2023-12-31,0.22,porcentaje
11,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.3: Con problemas (%),Situacion 3,2023-12-31,0.00,porcentaje
12,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.4: Con alto riesgo de insolvencia (%),Situacion 4,2023-12-31,0.05,porcentaje
13,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.09,porcentaje
14,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.TOTAL GARANTIZADO - Garantías Preferidas...,total,2023-12-31,6.60,porcentaje
15,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA DE CONSUMO O VIVIENDA ($),total,2023-12-31,1134529.54,monto
17,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.1: En situación normal (%),Situacion 1,2023-12-31,94.14,porcentaje
18,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,1.70,porcentaje
19,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,1.60,porcentaje
20,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.86,porcentaje
21,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.69,porcentaje
22,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.TOTAL GARANTIZADO - Garantías Preferidas...,total,2023-12-31,9.68,porcentaje
23,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA COMERCIAL ASIMILABLE A CONSUMO ($),total,2023-12-31,686501.13,monto
25,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.1: En situación normal (%),Situacion 1,2023-12-31,96.78,porcentaje
26,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,0.91,porcentaje
27,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,0.60,porcentaje
28,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.07,porcentaje
29,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.64,porcentaje
30,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.TOTAL GARANTIZADO - Garantías Preferidas...,total,2023-12-31,10.87,porcentaje
31,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,Previsiones por riesgo de incobrabilidad const...,total,2023-12-31,84225.25,monto
32,00011,BANCO DE LA NACION ARGENTINA,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),total,2023-12-31,4539600.89,monto

In [32]:
# Eliminar registros donde aparece: "TOTAL GARANTIZADO|Previsiones por riesgo de incobrabilidad"

mask_excluir = df1["denominacion"].str.contains(
    r"TOTAL GARANTIZADO|Previsiones por riesgo de incobrabilidad",
    case=False,
    na=False
)

df1 = df1[~mask_excluir].copy()

In [33]:
df1.head(30)

,codigo_entidad,nombre_entidad,denominacion,situacion,fecha,valor,formato
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),total,2023-12-31,2814492.63,monto
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.1: En situación normal (%),Situacion 1,2023-12-31,96.73,porcentaje
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.2: Con seguimiento especial/Riesgo bajo...,Situacion 2,2023-12-31,0.99,porcentaje
3,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.3: Con problemas/Riesgo medio (%),Situacion 3,2023-12-31,0.79,porcentaje
4,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.4: Con alto riesgo de insolvencia/Riesg...,Situacion 4,2023-12-31,1.03,porcentaje
5,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,TF.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.46,porcentaje
7,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA COMERCIAL ($),total,2023-12-31,993461.97,monto
9,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.1: En situación normal (%),Situacion 1,2023-12-31,99.64,porcentaje
10,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.2: Con seguimiento especial (%),Situacion 2,2023-12-31,0.22,porcentaje
11,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.3: Con problemas (%),Situacion 3,2023-12-31,0.00,porcentaje
12,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.4: Con alto riesgo de insolvencia (%),Situacion 4,2023-12-31,0.05,porcentaje
13,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.09,porcentaje
15,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA DE CONSUMO O VIVIENDA ($),total,2023-12-31,1134529.54,monto
17,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.1: En situación normal (%),Situacion 1,2023-12-31,94.14,porcentaje
18,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,1.70,porcentaje
19,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,1.60,porcentaje
20,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.86,porcentaje
21,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.69,porcentaje
23,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA COMERCIAL ASIMILABLE A CONSUMO ($),total,2023-12-31,686501.13,monto
25,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.1: En situación normal (%),Situacion 1,2023-12-31,96.78,porcentaje
26,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,0.91,porcentaje
27,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,0.60,porcentaje
28,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.07,porcentaje
29,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.64,porcentaje
32,00011,BANCO DE LA NACION ARGENTINA,TOTAL DE FINANCIACIONES Y GARANTIAS OTORGADAS ($),total,2023-12-31,4539600.89,monto
33,00011,BANCO DE LA NACION ARGENTINA,TF.Sit.1: En situación normal (%),Situacion 1,2023-12-31,86.81,porcentaje
34,00011,BANCO DE LA NACION ARGENTINA,TF.Sit.2: Con seguimiento especial/Riesgo bajo...,Situacion 2,2023-12-31,2.06,porcentaje
35,00011,BANCO DE LA NACION ARGENTINA,TF.Sit.3: Con problemas/Riesgo medio (%),Situacion 3,2023-12-31,0.56,porcentaje
36,00011,BANCO DE LA NACION ARGENTINA,TF.Sit.4: Con alto riesgo de insolvencia/Riesg...,Situacion 4,2023-12-31,0.88,porcentaje
37,00011,BANCO DE LA NACION ARGENTINA,TF.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,9.70,porcentaje

In [34]:
# Eliminar registros donde aparece: "^TOTAL DE FINANCIACIONES|^TF\.Sit"

mask_tf = df1["denominacion"].str.contains(
    r"^TOTAL DE FINANCIACIONES|^TF\.Sit",
    case=False,
    na=False
)

df1 = df1[~mask_tf].copy()

In [35]:
df1.head(30)

,codigo_entidad,nombre_entidad,denominacion,situacion,fecha,valor,formato
7,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA COMERCIAL ($),total,2023-12-31,993461.97,monto
9,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.1: En situación normal (%),Situacion 1,2023-12-31,99.64,porcentaje
10,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.2: Con seguimiento especial (%),Situacion 2,2023-12-31,0.22,porcentaje
11,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.3: Con problemas (%),Situacion 3,2023-12-31,0.00,porcentaje
12,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.4: Con alto riesgo de insolvencia (%),Situacion 4,2023-12-31,0.05,porcentaje
13,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.09,porcentaje
15,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA DE CONSUMO O VIVIENDA ($),total,2023-12-31,1134529.54,monto
17,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.1: En situación normal (%),Situacion 1,2023-12-31,94.14,porcentaje
18,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,1.70,porcentaje
19,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,1.60,porcentaje
20,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.86,porcentaje
21,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.69,porcentaje
23,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA COMERCIAL ASIMILABLE A CONSUMO ($),total,2023-12-31,686501.13,monto
25,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.1: En situación normal (%),Situacion 1,2023-12-31,96.78,porcentaje
26,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,0.91,porcentaje
27,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,0.60,porcentaje
28,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.07,porcentaje
29,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.64,porcentaje
39,00011,BANCO DE LA NACION ARGENTINA,CARTERA COMERCIAL ($),total,2023-12-31,1860735.82,monto
41,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.1: En situación normal (%),Situacion 1,2023-12-31,73.82,porcentaje
42,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.2: Con seguimiento especial (%),Situacion 2,2023-12-31,2.35,porcentaje
43,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.3: Con problemas (%),Situacion 3,2023-12-31,0.28,porcentaje
44,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.4: Con alto riesgo de insolvencia (%),Situacion 4,2023-12-31,0.88,porcentaje
45,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,22.67,porcentaje
47,00011,BANCO DE LA NACION ARGENTINA,CARTERA DE CONSUMO O VIVIENDA ($),total,2023-12-31,1697556.48,monto
49,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.1: En situación normal (%),Situacion 1,2023-12-31,94.62,porcentaje
50,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,2.18,porcentaje
51,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,1.05,porcentaje
52,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.20,porcentaje
53,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.94,porcentaje

In [36]:
df1["cartera"] = np.select(
    [
        # orden IMPORTANTE (de más específico a más general)
        df1["denominacion"].str.contains(r"C\.CAC|ASIMILABLE A CONSUMO", case=False, na=False),
        df1["denominacion"].str.contains(r"C\.CON|CONSUMO O VIVIENDA", case=False, na=False),
        df1["denominacion"].str.contains(r"C\.COM|CARTERA COMERCIAL", case=False, na=False),
    ],
    [
        "comercial_asimilable_consumo",
        "consumo_vivienda",
        "comercial",
    ],
    default="sin_clasificar"
)

In [37]:
df1.head(30)

,codigo_entidad,nombre_entidad,denominacion,situacion,fecha,valor,formato,cartera
7,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA COMERCIAL ($),total,2023-12-31,993461.97,monto,comercial
9,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.1: En situación normal (%),Situacion 1,2023-12-31,99.64,porcentaje,comercial
10,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.2: Con seguimiento especial (%),Situacion 2,2023-12-31,0.22,porcentaje,comercial
11,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.3: Con problemas (%),Situacion 3,2023-12-31,0.00,porcentaje,comercial
12,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.4: Con alto riesgo de insolvencia (%),Situacion 4,2023-12-31,0.05,porcentaje,comercial
13,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.09,porcentaje,comercial
15,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA DE CONSUMO O VIVIENDA ($),total,2023-12-31,1134529.54,monto,consumo_vivienda
17,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.1: En situación normal (%),Situacion 1,2023-12-31,94.14,porcentaje,consumo_vivienda
18,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,1.70,porcentaje,consumo_vivienda
19,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,1.60,porcentaje,consumo_vivienda
20,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.86,porcentaje,consumo_vivienda
21,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.69,porcentaje,consumo_vivienda
23,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA COMERCIAL ASIMILABLE A CONSUMO ($),total,2023-12-31,686501.13,monto,comercial_asimilable_consumo
25,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.1: En situación normal (%),Situacion 1,2023-12-31,96.78,porcentaje,comercial_asimilable_consumo
26,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,0.91,porcentaje,comercial_asimilable_consumo
27,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,0.60,porcentaje,comercial_asimilable_consumo
28,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.07,porcentaje,comercial_asimilable_consumo
29,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.64,porcentaje,comercial_asimilable_consumo
39,00011,BANCO DE LA NACION ARGENTINA,CARTERA COMERCIAL ($),total,2023-12-31,1860735.82,monto,comercial
41,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.1: En situación normal (%),Situacion 1,2023-12-31,73.82,porcentaje,comercial
42,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.2: Con seguimiento especial (%),Situacion 2,2023-12-31,2.35,porcentaje,comercial
43,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.3: Con problemas (%),Situacion 3,2023-12-31,0.28,porcentaje,comercial
44,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.4: Con alto riesgo de insolvencia (%),Situacion 4,2023-12-31,0.88,porcentaje,comercial
45,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,22.67,porcentaje,comercial
47,00011,BANCO DE LA NACION ARGENTINA,CARTERA DE CONSUMO O VIVIENDA ($),total,2023-12-31,1697556.48,monto,consumo_vivienda
49,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.1: En situación normal (%),Situacion 1,2023-12-31,94.62,porcentaje,consumo_vivienda
50,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,2.18,porcentaje,consumo_vivienda
51,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,1.05,porcentaje,consumo_vivienda
52,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,1.20,porcentaje,consumo_vivienda
53,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,0.94,porcentaje,consumo_vivienda

In [38]:
df1

,codigo_entidad,nombre_entidad,denominacion,situacion,fecha,valor,formato,cartera
7,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,CARTERA COMERCIAL ($),total,2023-12-31,993461.97,monto,comercial
9,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.1: En situación normal (%),Situacion 1,2023-12-31,99.64,porcentaje,comercial
10,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.2: Con seguimiento especial (%),Situacion 2,2023-12-31,0.22,porcentaje,comercial
11,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.3: Con problemas (%),Situacion 3,2023-12-31,0.00,porcentaje,comercial
12,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.4: Con alto riesgo de insolvencia (%),Situacion 4,2023-12-31,0.05,porcentaje,comercial
...,...,...,...,...,...,...,...,...
11005,65203,CRÉDITO REGIONAL COMPAÑÍA FINANCIERA S.A.U.,C.CAC.Sit.1: En situación normal (%),Situacion 1,2025-11-30,0.17,porcentaje,comercial_asimilable_consumo
11006,65203,CRÉDITO REGIONAL COMPAÑÍA FINANCIERA S.A.U.,C.CAC.Sit.2: Riesgo bajo (%),Situacion 2,2025-11-30,0.00,porcentaje,comercial_asimilable_consumo
11007,65203,CRÉDITO REGIONAL COMPAÑÍA FINANCIERA S.A.U.,C.CAC.Sit.3: Riesgo medio (%),Situacion 3,2025-11-30,0.00,porcentaje,comercial_asimilable_consumo
11008,65203,CRÉDITO REGIONAL COMPAÑÍA FINANCIERA S.A.U.,C.CAC.Sit.4: Riesgo alto (%),Situacion 4,2025-11-30,94.58,porcentaje,comercial_asimilable_consumo
11009,65203,CRÉDITO REGIONAL COMPAÑÍA FINANCIERA S.A.U.,C.CAC.Sit.5: Irrecuperable (%),Situacion 5,2025-11-30,5.25,porcentaje,comercial_asimilable_consumo

In [39]:
# Separar montos y porcentaje

df_montos = df1[df1["formato"] == "monto"].copy()
df_porcentajes = df1[df1["formato"] == "porcentaje"].copy()

In [40]:
# Verificar tipo númerico
df_porcentajes["valor"] = pd.to_numeric(df_porcentajes["valor"], errors="coerce")
df_montos["valor"] = pd.to_numeric(df_montos["valor"], errors="coerce")

In [41]:
# Normalizar montos
df_montos["valor"] = df_montos["valor"] / 100

In [42]:
# Obtener el total de cada cartera para multiplicar los porcentajes 
df_totales = df_montos[df_montos["situacion"] == "total"].copy()

In [43]:
# nos quedamos solo con lo necesario
df_totales = df_totales[["codigo_entidad", "fecha", "cartera", "valor"]].rename(columns={"valor": "monto_total"})

In [44]:
# Combinar con df_porcentajes para calcular valores nominales 
df_porcentajes = df_porcentajes.merge(df_totales, on=["codigo_entidad", "fecha", "cartera"], how="left")

In [45]:
#Calcular valor nominal 
df_porcentajes["valor"] = (df_porcentajes["valor"]/100 * df_porcentajes["monto_total"])
df_porcentajes["formato"] = "monto"

In [46]:
# Dataset final
df_final = df_porcentajes.drop(columns=["monto_total"]).copy()

In [47]:
# Verificar cambios realizados
df_final.head(30)

,codigo_entidad,nombre_entidad,denominacion,situacion,fecha,valor,formato,cartera
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.1: En situación normal (%),Situacion 1,2023-12-31,9898.855069,monto,comercial
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.2: Con seguimiento especial (%),Situacion 2,2023-12-31,21.856163,monto,comercial
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.3: Con problemas (%),Situacion 3,2023-12-31,0.000000,monto,comercial
3,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.4: Con alto riesgo de insolvencia (%),Situacion 4,2023-12-31,4.967310,monto,comercial
4,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.COM.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,8.941158,monto,comercial
5,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.1: En situación normal (%),Situacion 1,2023-12-31,10680.461090,monto,consumo_vivienda
6,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,192.870022,monto,consumo_vivienda
7,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,181.524726,monto,consumo_vivienda
8,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,211.022494,monto,consumo_vivienda
9,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CON.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,78.282538,monto,consumo_vivienda
10,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.1: En situación normal (%),Situacion 1,2023-12-31,6643.957936,monto,comercial_asimilable_consumo
11,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,62.471603,monto,comercial_asimilable_consumo
12,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,41.190068,monto,comercial_asimilable_consumo
13,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,73.455621,monto,comercial_asimilable_consumo
14,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,C.CAC.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,43.936072,monto,comercial_asimilable_consumo
15,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.1: En situación normal (%),Situacion 1,2023-12-31,13735.951823,monto,comercial
16,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.2: Con seguimiento especial (%),Situacion 2,2023-12-31,437.272918,monto,comercial
17,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.3: Con problemas (%),Situacion 3,2023-12-31,52.100603,monto,comercial
18,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.4: Con alto riesgo de insolvencia (%),Situacion 4,2023-12-31,163.744752,monto,comercial
19,00011,BANCO DE LA NACION ARGENTINA,C.COM.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,4218.288104,monto,comercial
20,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.1: En situación normal (%),Situacion 1,2023-12-31,16062.279414,monto,consumo_vivienda
21,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,370.067313,monto,consumo_vivienda
22,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,178.243430,monto,consumo_vivienda
23,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,203.706778,monto,consumo_vivienda
24,00011,BANCO DE LA NACION ARGENTINA,C.CON.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,159.570309,monto,consumo_vivienda
25,00011,BANCO DE LA NACION ARGENTINA,C.CAC.Sit.1: En situación normal (%),Situacion 1,2023-12-31,9607.992503,monto,comercial_asimilable_consumo
26,00011,BANCO DE LA NACION ARGENTINA,C.CAC.Sit.2: Riesgo bajo (%),Situacion 2,2023-12-31,127.570118,monto,comercial_asimilable_consumo
27,00011,BANCO DE LA NACION ARGENTINA,C.CAC.Sit.3: Riesgo medio (%),Situacion 3,2023-12-31,22.570098,monto,comercial_asimilable_consumo
28,00011,BANCO DE LA NACION ARGENTINA,C.CAC.Sit.4: Riesgo alto (%),Situacion 4,2023-12-31,29.439258,monto,comercial_asimilable_consumo
29,00011,BANCO DE LA NACION ARGENTINA,C.CAC.Sit.5: Irrecuperable (%),Situacion 5,2023-12-31,24.532715,monto,comercial_asimilable_consumo

In [48]:
# Eliminar columnas innecesarias
df_final = df_final.drop(columns=["denominacion", "formato"])

In [49]:
# Reordenar columnas
df_final = df_final[["codigo_entidad", "nombre_entidad", "cartera", "situacion", "fecha", "valor"]]

In [50]:
# Verificar cambios realizados
df_final.head(10)

,codigo_entidad,nombre_entidad,cartera,situacion,fecha,valor
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 1,2023-12-31,9898.855069
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 2,2023-12-31,21.856163
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 3,2023-12-31,0.000000
3,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 4,2023-12-31,4.967310
4,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 5,2023-12-31,8.941158
5,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,consumo_vivienda,Situacion 1,2023-12-31,10680.461090
6,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,consumo_vivienda,Situacion 2,2023-12-31,192.870022
7,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,consumo_vivienda,Situacion 3,2023-12-31,181.524726
8,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,consumo_vivienda,Situacion 4,2023-12-31,211.022494
9,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,consumo_vivienda,Situacion 5,2023-12-31,78.282538

In [51]:
#Quitar notación científica al mostrar y al exportar
pd.options.display.float_format = '{:,.2f}'.format

In [52]:
df_final.head(10)

,codigo_entidad,nombre_entidad,cartera,situacion,fecha,valor
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 1,2023-12-31,"9,898.86"
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 2,2023-12-31,21.86
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 3,2023-12-31,0.00
3,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 4,2023-12-31,4.97
4,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 5,2023-12-31,8.94
5,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,consumo_vivienda,Situacion 1,2023-12-31,"10,680.46"
6,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,consumo_vivienda,Situacion 2,2023-12-31,192.87
7,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,consumo_vivienda,Situacion 3,2023-12-31,181.52
8,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,consumo_vivienda,Situacion 4,2023-12-31,211.02
9,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,consumo_vivienda,Situacion 5,2023-12-31,78.28

In [53]:
df_final["valor"] = df_final["valor"].astype(float)

In [54]:
df_final.head(5)

,codigo_entidad,nombre_entidad,cartera,situacion,fecha,valor
0,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 1,2023-12-31,"9,898.86"
1,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 2,2023-12-31,21.86
2,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 3,2023-12-31,0.00
3,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 4,2023-12-31,4.97
4,00007,BANCO DE GALICIA Y BUENOS AIRES S.A.,comercial,Situacion 5,2023-12-31,8.94

In [55]:
# Guardar dataframe limpio en formato csv

ruta = r'C:\Users\Usuario\Desktop\Proyectos\situacion deudores argentina\deudores_sistema_financiero_limpio.csv'
df_final.to_csv(ruta, index=False,  float_format="%.2f")

In [56]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4065 entries, 0 to 4064
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   codigo_entidad  4065 non-null   object
 1   nombre_entidad  4065 non-null   object
 2   cartera         4065 non-null   object
 3   situacion       4065 non-null   object
 4   fecha           4065 non-null   datetime64[ns]
 5   valor           4065 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 190.7+ KB